/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.99
 * Generated at: 2026-05-12 18:16:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>NexaBank – Secure Login</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        .login-card { background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.09); border-radius: 20px; padding: 2.5rem; backdrop-filter: blur(20px); }\n");
      out.write("        .demo-creds { background: rgba(0,198,167,0.07); border: 1px solid rgba(0,198,167,0.2); border-radius: 10px; padding: 1rem 1.25rem; margin-top: 1.5rem; font-size: 0.82rem; }\n");
      out.write("        .demo-row { display: flex; justify-content: space-between; margin-bottom: 0.3rem; }\n");
      out.write("        .demo-row:last-child { margin-bottom: 0; }\n");
      out.write("        .demo-label { color: var(--muted); }\n");
      out.write("        .demo-value { font-family: var(--mono); color: var(--accent); }\n");
      out.write("        .pass-wrapper { position: relative; }\n");
      out.write("        .pass-toggle { position: absolute; right: 1rem; top: 50%; transform: translateY(-50%); background: none; border: none; color: var(--muted); cursor: pointer; font-size: 1rem; padding: 0; }\n");
      out.write("        .pass-toggle:hover { color: var(--white); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"login-page\">\n");
      out.write("    <div class=\"login-box\">\n");
      out.write("        <div class=\"login-header\">\n");
      out.write("            <div class=\"login-logo\">🏦</div>\n");
      out.write("            <h1 class=\"login-title\">NexaBank</h1>\n");
      out.write("            <p class=\"login-subtitle\">Secure Mobile Banking Platform</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"login-card\">\n");
      out.write("            <h2 style=\"font-size:1.3rem; margin-bottom:1.5rem;\">Sign in to your account</h2>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("errorMsg") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    ⚠ ");
      out.print( request.getAttribute("errorMsg") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 if ("true".equals(request.getParameter("logout"))) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-success\">\n");
      out.write("                    ✓ You have been signed out securely.\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div id=\"clientError\" class=\"alert alert-error\" style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("            <form id=\"loginForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login\" method=\"POST\" novalidate>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"form-label\" for=\"username\">Username</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"text\"\n");
      out.write("                        id=\"username\"\n");
      out.write("                        name=\"username\"\n");
      out.write("                        class=\"form-control\"\n");
      out.write("                        placeholder=\"Enter your username\"\n");
      out.write("                        autocomplete=\"username\"\n");
      out.write("                        value=\"");
      out.print( request.getParameter("username") != null ? request.getParameter("username") : "" );
      out.write("\"\n");
      out.write("                    >\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"form-label\" for=\"password\">Password</label>\n");
      out.write("                    <div class=\"pass-wrapper\">\n");
      out.write("                        <input\n");
      out.write("                            type=\"password\"\n");
      out.write("                            id=\"password\"\n");
      out.write("                            name=\"password\"\n");
      out.write("                            class=\"form-control\"\n");
      out.write("                            placeholder=\"Enter your password\"\n");
      out.write("                            autocomplete=\"current-password\"\n");
      out.write("                        >\n");
      out.write("                        <button type=\"button\" class=\"pass-toggle\" onclick=\"togglePass()\">👁</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-full\" style=\"margin-top:0.5rem;\">\n");
      out.write("                    Sign In  →\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div class=\"demo-creds\">\n");
      out.write("                <div style=\"font-weight:600; color:var(--accent); margin-bottom:0.6rem;\">🔑 Demo Accounts</div>\n");
      out.write("                <div class=\"demo-row\"><span class=\"demo-label\">alice / password123</span><span class=\"demo-value\">₹75,000</span></div>\n");
      out.write("                <div class=\"demo-row\"><span class=\"demo-label\">bob / password123</span><span class=\"demo-value\">₹42,500</span></div>\n");
      out.write("                <div class=\"demo-row\"><span class=\"demo-label\">charlie / password123</span><span class=\"demo-value\">₹1,20,000</span></div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>\n");
      out.write("    function togglePass() {\n");
      out.write("        const p = document.getElementById('password');\n");
      out.write("        p.type = (p.type === 'password') ? 'text' : 'password';\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
