/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.99
 * Generated at: 2026-05-12 18:38:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bank.model.User;
import com.bank.model.Account;
import java.text.NumberFormat;
import java.util.Locale;

public final class transfer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.bank.model.Account");
    _jspx_imports_classes.add("com.bank.model.User");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    User    user    = (User)    session.getAttribute("user");
    Account account = (Account) session.getAttribute("account");
    if (user == null || account == null) {
        response.sendRedirect(request.getContextPath() + "/login");
        return;
    }
    NumberFormat nf = NumberFormat.getNumberInstance(new Locale("en","IN"));
    nf.setMinimumFractionDigits(2);
    nf.setMaximumFractionDigits(2);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>NexaBank – Fund Transfer</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar\">\n");
      out.write("    <div class=\"navbar-inner\">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/dashboard\" class=\"navbar-brand\">\n");
      out.write("            <div class=\"brand-icon\">🏦</div>\n");
      out.write("            <span class=\"brand-name\">Nexa<span>Bank</span></span>\n");
      out.write("        </a>\n");
      out.write("        <ul class=\"nav-links\">\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dashboard\">⬛ Dashboard</a></li>\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/transfer\" class=\"active\">↔ Transfer</a></li>\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/billpay\">🧾 Bill Pay</a></li>\n");
      out.write("            <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/history\">📋 History</a></li>\n");
      out.write("            <li class=\"nav-logout\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">⎋ Logout</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<main class=\"page-container\">\n");
      out.write("    <div class=\"page-header\">\n");
      out.write("        <h1>↔ Fund Transfer</h1>\n");
      out.write("        <p class=\"text-muted\">Transfer funds instantly to any NexaBank account</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div style=\"display:grid; grid-template-columns: 1.2fr 1fr; gap:2rem; align-items:start;\">\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div class=\"card card-lg\">\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("errorMsg") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">⚠ ");
      out.print( request.getAttribute("errorMsg") );
      out.write("</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("successMsg") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-success\">✓ ");
      out.print( request.getAttribute("successMsg") );
      out.write("</div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <div id=\"clientError\" class=\"alert alert-error\" style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("            <form id=\"transferForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/transfer\" method=\"POST\" novalidate>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"form-label\" for=\"receiverAccNo\">Receiver Account Number</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"text\"\n");
      out.write("                        id=\"receiverAccNo\"\n");
      out.write("                        name=\"receiverAccNo\"\n");
      out.write("                        class=\"form-control\"\n");
      out.write("                        placeholder=\"e.g. ACC1001002\"\n");
      out.write("                        maxlength=\"20\"\n");
      out.write("                    >\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"form-label\" for=\"amount\">Transfer Amount (₹)</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"number\"\n");
      out.write("                        id=\"amount\"\n");
      out.write("                        name=\"amount\"\n");
      out.write("                        class=\"form-control\"\n");
      out.write("                        placeholder=\"0.00\"\n");
      out.write("                        min=\"1\"\n");
      out.write("                        step=\"0.01\"\n");
      out.write("                    >\n");
      out.write("                    <div id=\"amountPreview\" style=\"display:none; margin-top:0.4rem; font-family:var(--mono); font-size:0.9rem; color:var(--accent);\"></div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label class=\"form-label\" for=\"remarks\">Remarks (Optional)</label>\n");
      out.write("                    <input\n");
      out.write("                        type=\"text\"\n");
      out.write("                        id=\"remarks\"\n");
      out.write("                        name=\"remarks\"\n");
      out.write("                        class=\"form-control\"\n");
      out.write("                        placeholder=\"Purpose of transfer\"\n");
      out.write("                        maxlength=\"100\"\n");
      out.write("                    >\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-full\">\n");
      out.write("                    Send Money →\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        <div>\n");
      out.write("            <div class=\"card mb-2\">\n");
      out.write("                <div class=\"section-title\">💳 Your Account</div>\n");
      out.write("                <div class=\"text-muted\" style=\"font-size:0.82rem; margin-bottom:0.3rem;\">Account Number</div>\n");
      out.write("                <div class=\"mono\" style=\"font-size:1rem; margin-bottom:1rem;\">");
      out.print( account.getAccountNo() );
      out.write("</div>\n");
      out.write("                <div class=\"text-muted\" style=\"font-size:0.82rem; margin-bottom:0.3rem;\">Available Balance</div>\n");
      out.write("                <div style=\"font-size:1.4rem; font-weight:700;\" class=\"text-accent\">\n");
      out.write("                    ₹");
      out.print( nf.format(account.getBalance()) );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card\" style=\"background:rgba(244,200,66,0.05); border-color:rgba(244,200,66,0.15);\">\n");
      out.write("                <div class=\"section-title text-gold\">⚠ Transfer Guidelines</div>\n");
      out.write("                <ul style=\"font-size:0.82rem; color:var(--muted); line-height:1.8; padding-left:1rem;\">\n");
      out.write("                    <li>Max transfer: ₹10,00,000 per transaction</li>\n");
      out.write("                    <li>Verify receiver account number carefully</li>\n");
      out.write("                    <li>Transfers are instant and irreversible</li>\n");
      out.write("                    <li>Receiver must have an active account</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/validation.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
